name: plugin_1
version: '1.0-SNAPSHOT'
main: com.ccc212.Plugin_1
commands:
  ccc212:
    description: "第一个插件"
    aliases: c
  backup:
    description: "备份"
    aliases: b
  setTimeRate:
    description: "改变时间流速"
